alkiranet/terraform-provider-alkira

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_credential_aws_vpc.go, alkira/resource_alkira_group.go, alkira/resource_alkira_segment.go
Convert resources' Id from int to string to consistent with Terraform
convention. This commit includes connector_aws_vpc, group and segment. Also,
gofmt one more time across.
=> AK-15710 Convert resource Id from int to string

alkira/provider.go
Add one explicit error message when provider failed to init due to credential
or incorrect tenant URL.
=> AK-16725 Add one explicit error message for porvider init failure

alkira/resource_alkira_connector_gcp_vpc.go
Update connector_gcp_vpc with read and update support. Switch billing_tags
and segment to billing_tag_ids and segment_id to be consistent across all
resources in the procider.
=> AK-17578 Update connector_gcp_vpc with new client functions

alkira/resource_alkira_credential_azure_vnet.go, docs/resources/credential_azure_vnet.md
subscription_id of credential_azure_vnet is not required for creating
credential anymore.
=> AK-20868 Change subscription_id of credential_azure_vnet as optional

alkira/resource_alkira_connector_azure_vnet.go, docs/resources/connector_azure_vnet.md, go.mod, go.sum, templates/resources/connector_azure_vnet.md.tmpl, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_aws_vpc.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_azure_vnet.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_cisco_sdwan.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_gcp_vpc.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_internet_exit.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_oci_vcn.go, vendor/modules.txt
Remove vnet_subscription_id and vnet_region from connector-azure-vnet. API
doesn't need them anymore. Also, update alkira-client-go to v0.8.4 for latest
API changes.
=> AK-22042 Remove deprecated vars from connector-azure-vnet

alkira/resource_alkira_connector_cisco_sdwan.go
Fix the allow_nat_exit value set in connector_cisco_sdwan. The value needs
to be opposite when passing to API.
=> AK-24537 Fix the allow_nat_exit value set in connector_cisco_sdwan

alkira/resource_alkira_service_pan_helper.go
Global protect blocks of service pan is optional if global protect is disabled.
Don't fail even if those optional fields are not provided.
=> AK-25355 Make global protect blocks of service pan optional

docs/guides/guides-connector-aws-vpc.md
Add a section for _Guides_ with broader documentation for using Alkira's Terraform provider. This will include building the _AWS VPC_  and any other resources required to support the connector configuration and custom routing options.
=> Add AWS VPC Connector Guide

alkira/resource_alkira_connector_ipsec.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec.go, vendor/modules.txt
Reserver endpoint ID of connector_ipsec to avoid delete/create case when updating
the connector.
+ Pick up alkira-client-go v1.32.2 with the new connector_ipsec fields.
=> AK-26491 Reserve endpoint ID of connector_ipsec

alkira/resource_alkira_internet_applications.go, alkira/resource_alkira_segment.go, docs/resources/internet_application.md, docs/resources/segment.md
+ Add new `internet_protocol` to alkira_internet_application to select used protocol.
+ Add new arguments to segment to allow translation of IPv6 to IPv4 and specify source IPv4 pool.
=> AK-26615 Add IPv6 support to alkira_internet_application

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Add new license_sub_type to service_pan to allow select MODEL_BASED or CREDIT_BASED
under the existing license type.
=> AK-26616 Add new sub license support for service_pan

alkira/resource_alkira_connector_aruba_edge.go, alkira/resource_alkira_connector_aruba_edge_helper.go, alkira/resource_alkira_connector_cisco_sdwan.go, alkira/resource_alkira_service_fortinet.go, alkira/resource_alkira_service_fortinet_helper.go, alkira/resource_alkira_service_pan.go, alkira/resource_alkira_service_pan_helper.go, docs/resources/connector_aruba_edge.md, docs/resources/connector_cisco_sdwan.md, docs/resources/service_fortinet.md, docs/resources/service_pan.md
Switch from TypeSet to TypeList to avoid diff issue when updating resources.
+ Update connector_aruba_edge instances block to use TypeList.
+ Update connector_cisco_sdwan vedge block to use TypeList.
+ Update service_fortinet isntances block to use TypeList.
+ Update service_pan instance block to use TypeList.
=> AK-27110 Update some connector and service resoruces to use TypeList

.github/workflows/acceptance.yml
Terraform destroy must run to clean up even if Terraform apply fails.
=> AK-27457 Update acceptance.yml for acceptance action to destroy always

alkira/resource_alkira_service_pan_helper.go
Fix the random string in service-pan instance name. The auto generated name string should be only used for the hidden PAN instance credential.
=> AK-28129 Fix the random string in serivce-pan instance name

alkira/resource_alkira_credential_fortinet.go, alkira/resource_alkira_credential_fortinet_instance.go, alkira/resource_alkira_service_fortinet.go, alkira/resource_alkira_service_fortinet_helper.go, docs/resources/credential_fortinet_instance.md, docs/resources/service_fortinet.md, examples/resources/alkira_service_fortinet/resource.tf
Moved fortinet credentials and fortinet instance credentials into fortinet service. Added deprecation messages. Fixed license_type duplication, only required in service_fortinet.
=> AK-28216 Deprecate fortinet credential resources

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Mark pan_username and pan_password as "Required" in service_pan. Those two are always required now.
=> AK-28710 Mark username and password required in service_pan

alkira/resource_alkira_service_infoblox.go, docs/resources/service_infoblox.md
Update service_infoblox to only allow license BYOL. PAY_AS_YOU_GO is not supported anywhere.
=> AK-28795 Update license of service_infoblox to only allow BYOL

alkira/resource_alkira_connector_ipsec_helper.go
Set availability for both static and dynamic routing when routing_type is specified as BOTH.
=> AK-30188 Set Availability when routing_type is BOTH in connector_ipsec

alkira/resource_alkira_segment.go, docs/resources/segment.md
Mark several fields that is behind feature flags as BETA to avoid confusion.
=> AK-30729 Mark several fields in segment resource as BETA

acceptance/service_zscaler.tf, alkira/resource_alkira_service_zscaler.go, docs/resources/service_zscaler.md
Mark ping_probe_ip as optional in service_zscaler and add acceptance test for the service.
=> AK-32309 Mark ping_probe_ip as optional in service_zscaler

alkira/resource_alkira_connector_aruba_edge.go, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_internet_exit.go, alkira/resource_alkira_connector_oci_vcn.go, alkira/resource_alkira_service_checkpoint.go, alkira/resource_alkira_service_fortinet.go, docs/resources/connector_gcp_vpc.md
Avoid sending empty error to diag.FromErr function that cause a crash.
=> AK-33142 Fix passing empty err to diag function

acceptance/main.tf, acceptance/service_checkpoint.tf, alkira/resource_alkira_service_checkpoint.go, alkira/resource_alkira_service_checkpoint_helper.go, docs/resources/service_checkpoint.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/credentials.go, vendor/github.com/alkiranet/alkira-client-go/alkira/flow_collector.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_traffic_rules.go, vendor/github.com/alkiranet/alkira-client-go/alkira/segment_resource.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_checkpoint.go, vendor/modules.txt
The segment in management_server of service_checkpoint is optional and it should be not sent in API.
+ Upgrade alkira-client-go to v1.39.0 to pick client fixes.
+ Rename "user_name" to "username" in management_server to be consistent.
+ Rename "management_server_password" to "password" to avoid duplicated name with block.
+ Update acceptance tests with new coverage case with management_server type as SMS.
=> AK-34849 Fix optional segment issues with service_checkpoint

acceptance/policy_nat.tf, alkira/resource_alkira_policy_nat.go, alkira/resource_alkira_policy_nat_rule.go, docs/resources/policy_nat.md, docs/resources/policy_nat_rule.md
Update default value of category with "DEFAULT" in policy_nat and policy_nat_rule.
+ Update documentation with clearer descriptions.
+ Update acceptance tests with policy_nat.
=> AK-35713 Update default value of category in NAT policy resources

alkira/resource_alkira_connector_azure_vnet_helper.go
Revert changes to azure vnet connector UDR.
The backend now handles the nil values.
Also this code did not do anything as the UdrLists struct would be initalized with nil (default values) values when nothing was passed by the helper function.
=> Cleanup udr in azure vnet connector.

alkira/resource_alkira_connector_aruba_edge.go, alkira/resource_alkira_connector_aruba_edge_helper.go, docs/resources/connector_aruba_edge.md, examples/resources/alkira_connector_aruba_edge/resource.tf
the aruba_edge_connect_segment used to take the id, instead of a name and it would then query the Alkira API to find the segment name of the Aruba segment, which would fail.
Now we take the aruba segment name and pass it onto the API.
=> AK-46000 - fixed aruba_edge_connect_segment.

acceptance/lists.tf, acceptance/service_cisco_fdtv.tf, alkira/resource_alkira_segment.go, alkira/resource_alkira_service_checkpoint_helper.go, alkira/resource_alkira_service_cisco_ftdv_helper.go, alkira/resource_alkira_service_pan_helper.go, docs/resources/connector_azure_expressroute.md, docs/resources/segment.md, docs/resources/service_pan.md
Update acceptance tests to adapt new validations after new REL49 upgrade.
+ Update Cisco FDTV version.
+ Update global CIDR list for FDTV.
+ Disable overlapping validation in segment.
=> AK-46447 Update acceptance tests to pass after REL49 upgrade

alkira/resource_alkira_connector_cisco_sdwan.go, docs/resources/connector_cisco_sdwan.md, docs/resources/service_pan.md, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_cisco_sdwan.go
add tunnel_protocol support for Cisco SDWAN
update docs.
removed `enable_traffic` field from PAN docs.
=> AK-46148 - add tunnel_protocol support for Cisco SDWAN

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_oci_vcn.go, docs/resources/connector_aws_vpc.md, docs/resources/connector_azure_expressroute.md, docs/resources/connector_azure_vnet.md, docs/resources/connector_gcp_vpc.md, docs/resources/connector_oci_vcn.md
AWS VPC, Azure VNET, GCP VPC and OCI VCN now support  `5XSMALL` and `XSMALL` sizes.
As discussed previously , removed size validations from the provider, the sizes will be validated in the back-end.
=> AK-47183 - Size Validations for some Cloud connectors

alkira/resource_alkira_connector_azure_expressroute.go, alkira/resource_alkira_connector_azure_expressroute_helper.go, docs/resources/connector_azure_expressroute.md
properly set the segmentName for the global segmentOptions.
Make all the fields required inside customer gateway tunnel.
=> AK-54500 and AK-54504 - properly set the segmentName for the global segmentOptions

alkira/resource_alkira_connector_azure_expressroute.go, docs/resources/connector_azure_expressroute.md
If `ike_version` is sent in the payload, other fields like remote auth are required by the API.
=> AK-54865 - remove default value for `ike_version`.

alkira/resource_alkira_probe_tcp.go, alkira/resource_alkira_probe_tcp_helper.go, docs/resources/probe_http.md, docs/resources/probe_https.md, docs/resources/probe_tcp.md, examples/resources/alkira_probe_http/resource1.tf, examples/resources/alkira_probe_https/resource1.tf, examples/resources/alkira_probe_https/resource2.tf, examples/resources/alkira_probe_tcp/resource.tf, examples/resources/alkira_probe_tcp/resource1.tf
make tcp probe schema consistent with other probes. also fix examples and docs.
=> AK-56066 - make tcp probe schema consistent with other probe types.

alkira/resource_alkira_policy_routing.go, alkira/resource_alkira_policy_routing_helper.go, docs/resources/policy_routing.md, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_route.go
set.asPathReplaceWithSegmentAsn will accept comma separated string of ASNs or ALL - these are the ASNs that will be replaced with the local segment ASN. Can be null
=> AK-55832 - add new fields to route policy for branch connectors.

alkira/resource_alkira_policy_routing.go, alkira/resource_alkira_policy_routing_helper.go, docs/resources/policy_routing.md, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_route.go
targetConnectorCategory to differentiate between traditional (on-prem) and cloud-based route policies.
sourceRoutesPrefixListId used to source routes from cloud connectors 
set.med BGP attribute used to suggest the preferred path into a network. Lower values are more preferred.
=> AK-55863 - support new fields for route policy

acceptance/lists.tf, acceptance/service_checkpoint.tf, alkira/resource_alkira_policy_nat_rule.go, alkira/resource_alkira_policy_nat_rule_helper.go, docs/resources/policy_nat_rule.md, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_nat_rules.go
A new field called direction(INBOUND/OUTBOUND) is added to the NATRule.
The following fields are added to action.destinationNatTranslation,
routingOptions : {
"trackPrefixes": [],
"trackPrefixListIds": [],
"invalidateRoutingTrackPrefixes": null/Boolean
}
=> AK-55834 - update nat rules policy

alkira/resource_alkira_connector_azure_expressroute.go
Adds a computed field for the implicit group ID associated with the connector.
Refs: AK-59340
=> AK-59340 - expose `implicit_group_id` for Azure express route

vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec_adv.go
This change modifies the `BgpAuthKeyAlkira` field in both `ConnectorIPSecDynamicRouting` and `ConnectorAdvIPSecDynamicRouting` structs to be optional by adding the `omitempty` tag. This ensures that the field is not included in JSON marshaling when empty, which aligns with API expectations and prevents potential validation issues.
=> AK-59844 - make bgpAuthKeyAlkira optional in ipsec connectors
