alkiranet/terraform-provider-alkira

alkira/data_source_alkira_group.go
Add data resource support for group
=> AK-14185 Add data resource for group

alkira/data_source_alkira_policy_prefix_list.go, alkira/provider.go, alkira/provider_test.go
Add data source support for policy prefix list to all user to use already
created policy prefix list.
=> AK-14184 Implement data source for policy prefix list

alkira/resource_alkira_billing_tag.go, examples/resources/alkira_billing_tag/resource.tf
Add support of Description field for Billing Tag.
=> AK-13448 Add Description field for Billing Tag

alkira/helper.go
Processing vpc_subnet when it's specified as part of the routing options.
=> AK-16414 Fix the ignored vpc_subnet in connector_aws_vpc

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_ipsec.go
Implement update function for connector aws_vpc, azure_vnet and ipsec.
=> AK-16248 Implement update for connector aws_vpc, azure_vnet and ipsec.

alkira/resource_alkira_connector_aws_vpc.go, docs/resources/connector_aws_vpc.md
Update connector-aws-vpc documentation to reflect latest changes and elaborate
more details about the usage. Add validation for size of the connector.
=> AK-16248 Update connector-aws-vpc doucmentation

docs/resources/connector_aws_vpc.md
Update connector-aws-vpc examples in documentation to indicate the
latest changes.
=> AK-16806 Update the connector-aws-vpc examples

alkira/resource_alkira_connector_ipsec_helper.go
Fix the disable_advertise_on_prem_routes variable that should be reversed in the
API call.
=> AK-17112 Fix the disable_advertise_on_prem_routes in connector_ipsc

docs/resources/connector_ipsec.md
Add more details in doc to explain the usage of vpn_mode.
=> AK-17297 Add more details for vpn_mode in connector-ipsec doc

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Update default value documation for MaxInstanceCount and MinInstanceCount to be
more informative.
=> AK-17936 Update variables (*InstanceCount) doc for service PAN

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Remove deprecated group var from service-pan.
=> AK-17934 Remove deprecated group var from service-pan

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
The credential_id is required var for service-pan.
=> AK-17932 Fix service-pan to mark credential_id as required

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Mark panorama_enabled as optional with default value to false in service-pan.
=> AK-17935 Mark panorama_enabled as optional with default value to false

alkira/resource_alkira_service_pan.go
Mark groups field in service-pan as optional.
=> AK-18674 Mark groups field in service-pan as optional

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_cisco_sdwan.go, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_policy.go, alkira/resource_alkira_policy_prefix_list.go, alkira/resource_alkira_policy_rule.go, alkira/resource_alkira_policy_rule_list.go
Update resources to compile with alkira-client-go v0.7.0.
=> AK-18729 Compile with alkira-client-go v0.7.0

alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_ipsec_helper.go, docs/resources/connector_ipsec.md
Remove deprecated field customer_gw_asn from connector-ipsec.
=> AK-17126 Remove deprecated customer_gw_asn from connector-ipsec

alkira/resource_alkira_policy_rule_list.go
Enable update functionality for policy_rule_list.
=> AK-18540 Enable update for policy_rule_list

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Update service-pan documentation for max_instance_count and remove its
default value.
=> AK-18674 Update service-pan documentation for max_instance_count

alkira/resource_alkira_policy_rule_list.go
Refactor policy_rule_list with latest client function and add update, read.
=> AK-18540 Refactor policy_rule_list with latest client APIs

alkira/resource_alkira_policy_rule.go
Refactor policy_rule with update and read functions. Add new variables
src_prefix_list_ids and dst_prefix_list_ids.
=> AK-18355 Refactor policy_rule resource and add prefix list support

alkira/resource_alkira_connector_ipsec.go, docs/resources/connector_ipsec.md
Add availability field for status routing in connector-ipsec.
=> AK-17151 Add availability field for static routing in connector-ipsec

alkira/resource_alkira_service_pan.go
Update service-pan with latest client APIs with support for update and read.
=> AK-18850 Update service-pan with latest client APIs

alkira/resource_alkira_policy.go
Refactor resource policy with latest client APIs to enable read, update, etc.
=> AK-17885 Refactor resource policy with latest client APIs

alkira/resource_alkira_connector_aws_vpc.go
Update connector_aws_vpc with read support and switch both billing_tags and
segment to billing_tag_ids and segment_id.
=> AK-17576 Update connector_aws_vpc with read support and ids

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go
Update connector_azure_vnet with read functions and convert both billing tags
and segment to billing_tag_ids and segment_ids.
=> AK-17577 Update connector_azure_vnet with read function and ids

alkira/resource_alkira_connector_ipsec.go
Update connector-ipsec with new client APIs and add read support.
+ Switching billing_tags to billing_tag_ids.
+ Switching segment to segment_id.
=> AK-17579 Update connector-ipsec with new client APIs

alkira/resource_alkira_internet_applications.go
Update internet_application with read and update support with latest
client APIs.
+ Switch billing_tags to billing_tag_ids
+ Switch segment to segment_ids
=> AK-18954 Refactor internet_application with latest client APIs

docs/resources/connector_gcp_vpc.md, examples/resources/alkira_connector_gcp_vpc/resource.tf
Update the example of connector_gcp_vpc with latest API changes.
=> AK-16853 Update connector_gcp_vpc documentation

alkira/resource_alkira_connector_cisco_sdwan.go, docs/resources/connector_cisco_sdwan.md
Mark both hostname and cloud_init_file as required in connector_cisco_sdwan.
=> AK-20008 Adjust required fields for connector_cisco_sdwan

alkira/resource_alkira_connector_azure_vnet.go
Update variables to read in connector_azure_vnet.
=> AK-20168 Update variables for read in connector_azure_vnet

alkira/resource_alkira_connector_ipsec.go, templates/resources/connector_ipsec.md.tmpl
Add billing_tag_ids to endpoint section of connector_ipsec.
=> AK-17710 Add billing_tag_ids to connector_ipsec's endpoint

alkira/resource_alkira_connector_cisco_sdwan.go, docs/resources/connector_cisco_sdwan.md
Add the new type field to connector_cisco_sdwan to support new types of
Cisco SDWAN.
=> AK-20013 Add type field to connector_cisco_sdwan

alkira/helper.go, alkira/resource_alkira_billing_tag.go, alkira/resource_alkira_connector_oci_vcn_helper.go, alkira/resource_alkira_group.go, alkira/resource_alkira_segment.go, alkira/resource_alkira_service_pan.go, alkira/resource_alkira_tenant_network.go, docs/resources/service_pan.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/client.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_pan.go, vendor/modules.txt
@spikewang Can you pay particular attention to the descriptions that I've added to the schema?
=> add support for global pan protect

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_cisco_sdwan.go, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_internet_exit.go, alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_oci_vcn.go, docs/resources/connector_aws_vpc.md, docs/resources/connector_azure_vnet.md, docs/resources/connector_cisco_sdwan.md, docs/resources/connector_gcp_vpc.md, docs/resources/connector_internet_exit.md, docs/resources/connector_ipsec.md, docs/resources/connector_oci_vcn.md, templates/resources/connector_aws_vpc.md.tmpl, templates/resources/connector_azure_vnet.md.tmpl, templates/resources/connector_ipsec.md.tmpl
Add new optional "enabled" field to all connnectors. The default value will
be true for all connectors.
=> AK-21408 Add enabled field to all connectors

alkira/resource_alkira_connector_aws_vpc.go, docs/resources/connector_aws_vpc.md, templates/resources/connector_aws_vpc.md.tmpl
Add the new optional direct_inter_vpc_communication option to
connector-aws-vpc resource.
=> AK-19833 Add new direct_inter_vpc option to connector-aws-vpc

alkira/resource_alkira_connector_azure_vnet.go, docs/resources/connector_azure_vnet.md, templates/resources/connector_azure_vnet.md.tmpl
Add optional new argument service_tags to connector_azure_vnet.
=> AK-21153 Add optional service_tags to connector_azure_vnet

alkira/resource_alkira_segment.go, docs/resources/segment.md
Mark "asn" argument in alkira_segment as optional with default value of
65514.
=> AK-22536 Mark asn argument in alkira_segment resource as optional

alkira/data_source_alkira_group.go, alkira/helper.go, alkira/resource_alkira_group.go, alkira/resource_alkira_service_pan.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/byoip.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_akamai_prolexic.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_azure_vnet.go, vendor/github.com/alkiranet/alkira-client-go/alkira/credentials.go, vendor/github.com/alkiranet/alkira-client-go/alkira/fortinet.go, vendor/github.com/alkiranet/alkira-client-go/alkira/group_connector.go, vendor/github.com/alkiranet/alkira-client-go/alkira/group_user.go, vendor/github.com/alkiranet/alkira-client-go/alkira/segment_resource.go, vendor/github.com/alkiranet/alkira-client-go/alkira/segment_resource_share.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_pan.go, vendor/modules.txt
Upgrade alkira-client-go to v0.9.1 with new features and bug fixes.
=> AK-22839 Update to alkira-client-go v0.9.1

alkira/resource_alkira_internet_applications.go, docs/resources/internet_application.md
Fix the wrong type of connector_id of internet_application.
=> AK-21257 Fix the wrong type of connector_id of internet_application

alkira/resource_alkira_connector_azure_vnet.go, docs/resources/connector_azure_vnet.md, templates/resources/connector_azure_vnet.md.tmpl
Fix the formation issue in connector_azure_vnet doc of service_tags.
=> AK-22939 Fix the formation issue in connector_azure_vnet doc

alkira/resource_alkira_credential_gcp_vpc.go, docs/resources/credential_gcp_vpc.md
Update GCP credential to make some uncessary arguments as optional
and update the documenation.
=> AK-11271 Update GCP credential fields and documenation

alkira/resource_alkira_internet_applications.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/credentials.go, vendor/github.com/alkiranet/alkira-client-go/alkira/internet_applications.go, vendor/github.com/alkiranet/alkira-client-go/alkira/list_prefixes.go, vendor/modules.txt
Update alkira-client-go to v0.9.3.
=> AK-22989 Update alkira-client-go to v0.9.3

alkira/resource_alkira_internet_applications.go, alkira/resource_alkira_internet_applications_helper.go, docs/resources/connector_internet_exit.md, docs/resources/internet_application.md, examples/resources/alkira_connector_internet_exit/resource.tf, examples/resources/alkira_internet_application/resource.tf
Update alkira_internet_application with latest features.
+ add target block.
+ add inbound arguments.
- private_ip and private_ports are deprecated.
=> AK-21257 Update alkira_internet_application with latest features

alkira/resource_alkira_segment.go, docs/resources/segment.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/segment.go, vendor/modules.txt
Add new "reserve_public_ips" argument to alkira_segment resource.
+ Pick changes from alkira-client-go v0.9.4.
+ update documentation
=> AK-23021 Add new field to alkira_segment

alkira/resource_alkira_connector_ipsec.go, templates/resources/connector_ipsec.md.tmpl
Add default value to availability field of IPSec connector.
=> AK-23246 Add default value to availability field of IPSec connector

alkira/resource_alkira_connector_cisco_sdwan.go, docs/resources/connector_cisco_sdwan.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_cisco_sdwan.go, vendor/modules.txt
Add customer_asn field to connector_cisco_sdwan and move alkira-client-go to
v0.9.6 to pick up the changes.
=> AK-23527 Add customer_asn field to connector_cisco_sdwan

alkira/resource_alkira_connector_cisco_sdwan.go
Enable setting type of connector_cisco_sdwan.
=> AK-23834 Enable setting type of connector_cisco_sdwan

alkira/resource_alkira_connector_ipsec_helper.go
Set the availability field of connector_ipsec based on the cases of routing
options.
=> AK-24070 Set the availability field of connector_ipsec by cases

alkira/resource_alkira_credential_azure_vnet.go, docs/resources/credential_azure_vnet.md
Add new variables to allow add credentials from ENV variables.
=> AK-24316 Allow ENV variable to set alkira_credential_azure_vnet

alkira/resource_alkira_credential_aws_vpc.go, alkira/resource_alkira_credential_azure_vnet.go, alkira/resource_alkira_credential_oci_vcn.go, docs/resources/credential_aws_vpc.md, docs/resources/credential_azure_vnet.md, docs/resources/credential_oci_vcn.md
Add ENV variable support for specifying credential_oci_vcn and update
aws_vpc and azure_vnet documentation.
=> AK-24343 Add ENV variable support for specifying credential_oci_vcn

alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_azure_vnet_helper.go, docs/resources/connector_azure_vnet.md, templates/resources/connector_azure_vnet.md.tmpl
Set the export routing options in connector_azure_vnet when vnet_cidr
or vnet_subnet block was used.
=> AK-24457 Set export routing field in connector_azure_vnet

alkira/helper.go, alkira/resource_alkira_connector_akamai_prolexic.go, alkira/resource_alkira_connector_aruba_edge_helper.go, alkira/resource_alkira_credential_aws_vpc.go, alkira/resource_alkira_credential_azure_vnet.go, alkira/resource_alkira_credential_checkpoint_helper.go, alkira/resource_alkira_credential_cisco_sdwan.go, alkira/resource_alkira_credential_fortinet.go, alkira/resource_alkira_credential_fortinet_instance.go, alkira/resource_alkira_credential_gcp_vpc.go, alkira/resource_alkira_credential_oci_vcn.go, alkira/resource_alkira_credential_pan.go, alkira/resource_alkira_credential_pan_instance.go, alkira/resource_alkira_service_infoblox.go, alkira/resource_alkira_service_infoblox_helper.go, alkira/resource_alkira_service_pan.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/credentials.go, vendor/github.com/alkiranet/alkira-client-go/alkira/internet_applications.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_fortinet.go, vendor/modules.txt
Update service-pan with registeration pin support and update credential
with expires support.
+ Move alkira-client-go to v1.30.3
=> AK-24579 Update serivce-pan with registration pin support

alkira/resource_alkira_internet_applications.go, alkira/resource_alkira_internet_applications_helper.go, docs/resources/internet_application.md
Add BYOIP support to internet_application and replace ports argument
with port_ranges.
=> AK-25449 Add BYOIPID support for internet_application

alkira/resource_alkira_service_pan.go, docs/resources/service_pan.md
Add master key support to service-pan.
- Add new argument master_key_enabled.
- Add new argument master_key.
- Add new argument master_key_expiry.
=> AK-25676 Add master key support to service-pan

alkira/resource_alkira_policy.go, alkira/resource_alkira_policy_nat_rule.go, alkira/resource_alkira_policy_rule.go, alkira/resource_alkira_policy_rule_list.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/client.go, vendor/github.com/alkiranet/alkira-client-go/alkira/internet_applications.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_nat_rules.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_route_policy.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_rule_lists.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_rules.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_traffic_policy.go, vendor/github.com/alkiranet/alkira-client-go/alkira/segment.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_pan.go, vendor/modules.txt
Update alkira-client-go to v1.32.1 for new features and tweaks.
=> AK-26267 Update to alkira-client-go v1.32.1

alkira/resource_alkira_connector_cisco_sdwan.go, docs/resources/connector_cisco_sdwan.md, docs/resources/service_infoblox.md, templates/guides/guides-connector-aws-vpc.md
Keep tracking vedge instance ID of connector_cisco_sdwan to avoid updating
issues.
+ Tracking vedge instance ID so update will not delete/create new ones.
+ Update all documenations.
=> AK-26491 Keep tracking vedge instance ID of connector_cisco_sdwan

go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_route_policy.go, vendor/github.com/alkiranet/alkira-client-go/alkira/segment.go, vendor/modules.txt
Update alkira-client-go to pick segment and routing policy fixes.
=> AK-26909 Update alkira-client-go to v1.32.3

alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_ipsec_helper.go, docs/resources/connector_ipsec.md
Switch endpoint block of connector_ipsec to TypeList to avoid generating uncessary
diff with TypeSet.
=> AK-27041 Switch endpoint of connector_ipsec to TypeList

alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_ipsec_helper.go, docs/resources/connector_ipsec.md, examples/resources/alkira_connector_ipsec/resource.tf
Enable and complete the advanced_options for each endpoint block in connector_ipsec.
+ Update and complete the advanced_options.
+ Update all documentation related to advanced_options.
+ Update example for advanced_options.
=> AK-27089 Enable advanced options for endpoint of connector_ipsec

docs/resources/segment_resource.md, examples/resources/alkira_segment_resource/resource.tf
Fix the example in documentation of alkira_segment_resource.
=> AK-27284 Fix the example of alkira_segment_resource

acceptance/billing_tags.tf, acceptance/byoip_prefix.tf, acceptance/group.tf, acceptance/lists.tf, acceptance/main.tf, acceptance/policy.tf, acceptance/segment.tf
Compiled and organized resources into following:
- billings tags
- BYOIP
- groups
- lists
- policies
- segments
=> Feature/AK-27232 Adding more configurations for acceptance testing.

alkira/resource_alkira_connector_ipsec_helper.go
Add additional validation for empty values of connector_ipsec endpoint block.
=> AK-27470 Add additional validation for connector_ipsec endpoint block

alkira/resource_alkira_credential_pan_instance.go, docs/resources/credential_pan_instance.md, docs/resources/service_infoblox.md
Make auth_code of credential_pan_instance optional.
=> AK-27471 Make auth_code of credential_pan_instance optional

alkira/resource_alkira_credential_pan_instance.go, docs/resources/credential_pan_instance.md
Make auth_key of credential_pan_instance optional and add additional details
in doc.
=> AK-27481 Make auth_key of credential_pan_instance optional

alkira/helper.go, alkira/resource_alkira_connector_ipsec.go, docs/resources/connector_ipsec.md
Add empty string validations for preshared_keys and billing_tag_ids in
connector_ipsec.
=> AK-27508 Add empty string validation in connector_ipsec

docs/resources/connector_cisco_sdwan.md, docs/resources/connector_gcp_vpc.md, docs/resources/connector_oci_vcn.md, docs/resources/policy.md, examples/resources/alkira_connector_aws_vpc/resource.tf, examples/resources/alkira_connector_cisco_sdwan/resource.tf, examples/resources/alkira_connector_gcp_vpc/resource.tf, examples/resources/alkira_connector_oci_vcn/resource.tf, examples/resources/alkira_policy/resource.tf
Update all examples with the new cidrs argument of segment resoruce.
=> AK-27651 Update documentation & examples with segment cidrs

alkira/resource_alkira_policy_nat_rule.go, docs/resources/policy_nat_rule.md
Update available translation_type of policy_nat_rules to remove not supported
DYNAMIC.
=> AK-27650 Update available translation_type of policy_nat_rules

go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_akamai_prolexic.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_aruba_edge.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_aws_vpc.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_azure_vnet.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_cisco_sdwan.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_gcp_vpc.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_internet_exit.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_oci_vcn.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_infoblox.go, vendor/modules.txt
Update alkira-client-go to 1.32.4 with minor API updates and tweaks.
=> AK-27723 Update alkira-client-go to v1.32.4

alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_ipsec_helper.go, docs/resources/connector_ipsec.md
Update connector_ipsec with latest changes:
+ Add ha_mode to specify HA mode for endpoint.
+ Add initiator in endpoint's advanced options.
+ Make preshared_keys of endpoint as required to avoid confusion.
=> AK-27717 Update connector_ipsec with new fields

alkira/resource_alkira_service_fortinet.go, docs/resources/service_fortinet.md
Make management_server_ip optional in service_fortinet.
=> AK-27844 Make management_server_ip optional in service_fortinet

alkira/resource_alkira_connector_akamai_prolexic.go, alkira/resource_alkira_connector_aruba_edge.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_cisco_sdwan.go, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_internet_exit.go, alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_oci_vcn.go, docs/resources/connector_akamai_prolexic.md, docs/resources/connector_aruba_edge.md, docs/resources/connector_aws_vpc.md, docs/resources/connector_azure_vnet.md, docs/resources/connector_cisco_sdwan.md, docs/resources/connector_gcp_vpc.md, docs/resources/connector_internet_exit.md, docs/resources/connector_ipsec.md, docs/resources/connector_oci_vcn.md
Expose implict_group_id from all connectors.
=> AK-27860 Expose implict_group_id from all connectors

alkira/resource_alkira_segment_resource.go, docs/resources/segment_resource.md
Expose auto-created implicit_group_id from segment resource.
=> AK-28041 Expose auto-created implicit_group_id from segment resource

alkira/resource_alkira_service_pan.go, docs/guides/release-notes-v0.9.6.md, docs/resources/service_pan.md, examples/resources/alkira_service_pan/resource.tf, templates/guides/release-notes-v0.9.6.md
Update documentation and make release note for v0.9.6
=> AK-28060 Update documentation and release note for v0.9.6

GNUmakefile, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/client.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_aws_vpc.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_azure_vnet.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_gcp_vpc.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_oci_vcn.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_remote_access.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_remote_access_template.go, vendor/modules.txt
Update alkira-client-go to v1.34.0 with all REL34 related API changes.
=> AK-28043 Update alkira-client-go to v1.34.0

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_oci_vcn.go, docs/resources/connector_aws_vpc.md, docs/resources/connector_azure_vnet.md, docs/resources/connector_gcp_vpc.md, docs/resources/connector_oci_vcn.md
Add optional failover_cxps argument to all cloud connector resources (connector_aws_vpc, connector_azure_vnet, connector_gcp_vpc, connector_oci_vcn).
=> AK-29104 Add failover_cxps to all cloud connector resources

alkira/resource_alkira_segment.go, docs/resources/segment.md
Add optional enterprise_dns_server_ip in segment resource.
=> AK-29224 Add enterprise_dns_server_ip in segment resource

alkira/resource_alkira_policy_nat_rule.go, docs/resources/policy_nat_rule.md
Set the default value of the action block of policy_nat_rule.
=> AK-28132 Set the default value of action block of policy_nat_rule

alkira/resource_alkira_connector_oci_vcn.go, docs/resources/connector_oci_vcn.md
Remove deprecated primary field in connector_oci_vcn resource.
=> AK-29404 Remove primary field in connector_oci_vcn resource

docs/guides/release-notes-v0.9.1.md, docs/guides/release-notes-v0.9.2.md, docs/guides/release-notes-v0.9.3.md, docs/guides/release-notes-v0.9.4.md, docs/guides/release-notes-v0.9.5.md, docs/guides/release-notes-v0.9.6.md, templates/guides/release-notes-v0.9.1.md, templates/guides/release-notes-v0.9.2.md, templates/guides/release-notes-v0.9.3.md, templates/guides/release-notes-v0.9.4.md, templates/guides/release-notes-v0.9.5.md, templates/guides/release-notes-v0.9.6.md
Reformat the previous release notes to look better after rendering on Terraform Registry.
=> AK-29457 Reformat the previous release notes to look better

alkira/resource_alkira_connector_ipsec.go, docs/resources/connector_ipsec.md
Make endpoint in connector-ipsec required. At least 1 endpoint block should be defined.
=> AK-29666 Make endpoint in connector-ipsec required

go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/client.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_internet_exit.go, vendor/github.com/alkiranet/alkira-client-go/alkira/internet_applications.go, vendor/github.com/alkiranet/alkira-client-go/alkira/list_global_cidr.go, vendor/modules.txt
Update alkira-client-go to v1.34.2.
=> AK-29723 Update alkira-client-go to v1.34.2

acceptance/cisco_ftdv.tf, acceptance/lists.tf, acceptance/segment.tf
=> AK-30133 Adding cisco ftdv connector and global cidr list with tags to acceptance test

alkira/resource_alkira_internet_applications.go, docs/resources/internet_application.md
Enable internet_protocol in internet_application.
=> AK-29751 Enable internet_protocol in internet_application

acceptance/segment.tf, alkira/resource_alkira_segment.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/segment.go, vendor/modules.txt
Add optional description field to segment resource.
=> AK-29763 Add optional description field to segment resoruce

alkira/resource_alkira_policy_routing.go
Fix the enabled field that is not set in policy_routing.
=> AK-30495 Fix the enabled not set in policy_routing

acceptance/connector_cisco_fdtv.tf, acceptance/connector_internet_exit.tf, acceptance/connector_ipsec.tf, alkira/resource_alkira_connector_ipsec.go, docs/resources/connector_ipsec.md
Mark the new availablility field of connector_ipsec as BETA and add acceptance test for connector_ipsec.
=> AK-29386 Mark availability field of connector_ipsec as BETA

README.md
Update top README file with update information.
=> AK-30599 Update top README file with updated information

acceptance/lists.tf, alkira/resource_alkira_connector_cisco_sdwan.go, alkira/resource_alkira_connector_cisco_sdwan_helper.go, alkira/resource_alkira_policy_prefix_list.go, alkira/resource_alkira_policy_prefix_list_helper.go, docs/resources/policy_prefix_list.md
Add optional prefix_range to policy_prefix_list.
+ There could be mutli prefix_range block defined in the prefix_list.
+ Clean up read function in cisco_sdwan to make it cleaner.
=> AK-29230 Add prefix_range to policy_prefix_list

acceptance/connector_cisco_fdtv.tf, acceptance/lists.tf, acceptance/service_checkpoint.tf, alkira/resource_alkira_service_checkpoint.go, alkira/resource_alkira_service_checkpoint_helper.go, docs/resources/service_checkpoint.md, examples/resources/alkira_service_checkpoint/resource.tf
Add instance ID and name in service_checkpoint.
+ Add name to instance block
+ Add computed ID to instance block
+ Rename instances to instance to be consistent
+ Update examples and tests
=> AK-29716 Add instance ID in service_checkpoint

alkira/resource_alkira_service_pan.go, alkira/resource_alkira_service_pan_helper.go
Refactor instance read function of service_pan to handle empty cases.
=> AK-30641 Refactor instance read function of service_pan

alkira/resource_alkira_service_checkpoint.go, docs/resources/service_checkpoint.md
Update documentation of service_checkpoint with more descriptions of management server type and options.
=> AK-30636 Update documentation of service_checkpoint

docs/guides/release-notes-v0.9.8.md, templates/guides/release-notes-v0.9.8.md
=> AK-30667 Add release note for v0.9.8

acceptance/internet_application.tf, acceptance/policy.tf, alkira/resource_alkira_policy_rule.go, docs/resources/policy_rule.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/byoip.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_rules.go, vendor/modules.txt
Enable optional internet_application_id in policy_rule to allow using internet_application in policy rule.
+ Add acceptance test to cover the new rule and internet_application.
=> AK-30796 Enable optional internet_application_id in policy_rule

acceptance/service_pan.tf, alkira/resource_alkira_service_pan.go
Add VM-SIM support of service-pan.
=> AK-31919 Add VM-SIM support of service-pan

acceptance/policy.tf, alkira/helper.go, alkira/resource_alkira_connector_aruba_edge.go, alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_internet_exit.go, alkira/resource_alkira_internet_applications_helper.go, alkira/resource_alkira_policy_rule.go, alkira/resource_alkira_service_checkpoint.go, alkira/resource_alkira_service_cisco_ftdv.go, alkira/resource_alkira_service_cisco_ftdv_helper.go, alkira/resource_alkira_service_fortinet.go, alkira/resource_alkira_service_infoblox.go, alkira/resource_alkira_service_pan.go, alkira/resource_alkira_service_zscaler.go, docs/resources/connector_akamai_prolexic.md, docs/resources/service_fortinet.md, docs/resources/service_infoblox.md, docs/resources/service_pan.md, docs/resources/service_zscaler.md
Switch all segment_ids from TypeList to TypeSet to avoid ordering issue.
+ Refactor the segment helper functions to make it cleaner.
+ Update resources that uses getSegmentNameById.
=> AK-30765 Convert all segment_ids from TypeList to TypeSet

alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_segment.go, docs/resources/connector_azure_expressroute.md, docs/resources/connector_azure_vnet.md
Add optional connection_mode to connector_azure_vnet.
=> AK-33411 Add optional connection_mode to connector_azure_vnet

alkira/resource_alkira_segment_resource_share.go, docs/resources/segment_resource_share.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/api.go, vendor/github.com/alkiranet/alkira-client-go/alkira/client.go, vendor/github.com/alkiranet/alkira-client-go/alkira/segment_resource_share.go, vendor/modules.txt
Add optional description field to segment_resource_share
+ Update alkira-client-go to v1.38.0
=> AK-33660 Add optional description field to segment_resource_share

acceptance/billing_tag.tf, acceptance/group.tf, acceptance/lists.tf
Add data source tests to acceptance test.
=> AK-34527 Add data source tests to acceptance test

acceptance/segment_resource.tf, acceptance/service_checkpoint.tf, alkira/resource_alkira_segment_resource.go, docs/resources/segment_resource.md
Add optional description field to resource segment_resource_share.
=> AK-34069 Add optional field description to segment_resource_share

alkira/resource_alkira_connector_aruba_edge.go, alkira/resource_alkira_policy_routing.go, alkira/resource_alkira_policy_routing_helper.go, docs/resources/connector_aruba_edge.md, docs/resources/policy_routing.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_route.go, vendor/modules.txt
Make rule block optional in policy_routing and fix typos.
=> AK-35369 Make rule block optional in policy_routing

README.md, alkira/helper.go, alkira/provider.go, alkira/resource_alkira_connector_fortinet_sdwan.go, alkira/resource_alkira_connector_fortinet_sdwan_helper.go, alkira/resource_alkira_policy_routing_helper.go, alkira/resource_alkira_service_checkpoint_test.go, alkira/resource_alkira_service_infoblox_helper.go, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_fortinet_sdwan.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_ipsec.go, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_versa_sdwan.go, vendor/github.com/alkiranet/alkira-client-go/alkira/credentials.go, vendor/github.com/alkiranet/alkira-client-go/alkira/helper.go, vendor/github.com/alkiranet/alkira-client-go/alkira/lists.go, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_nat.go, vendor/modules.txt
Add resource connector_fortinet_sdwan
+ Pickup alkira-client-go v1.42.0
+ Update Golang to v1.20.6.
=> AK-36747 Add resource connector_fortinet_sdwan

alkira/resource_alkira_policy_nat.go
Add new optional field allow_overlapping_translated_source_addresses to policy_nat
=> AK-36047 Add new optional field to policy_nat

alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_azure_vnet_helper.go
Update read function to check vnet_cidr and vnet_subnets on connector_azure_vnet.
=> AK-37387 Update read function of connector_azure_vnet

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_aws_vpc_helper.go, alkira/resource_alkira_connector_azure_vnet_helper.go, docs/resources/connector_aws_vpc.md
+ Improve the read functionality of connector_aws_vpc to read tgw_attachement better.
+ Switch to TypeSet for unordered array to avoid diff.
+ Update documentation.
=> AK-38078 Improve read function of connector_aws_vpc

alkira/resource_alkira_policy_prefix_list.go
Use TypeSet for prefixes in policy_prefix_list resource.
=> AK-37996 Use TypeSet for prefixes in policy_prefix_list

.github/workflows/acceptance-preprod.yml, .github/workflows/acceptance-prod.yml, acceptance/connector_internet_exit.tf, acceptance/connector_ipsec.tf, acceptance/connector_versa_sdwan.tf, acceptance/connector_vmware_sdwan.tf, acceptance/lists.tf, acceptance/main.tf, acceptance/service_checkpoint.tf, acceptance/service_cisco_fdtv.tf, acceptance/service_fortinet.tf, acceptance/service_pan.tf, acceptance/service_zscaler.tf, acceptance/variables.tf, alkira/resource_alkira_connector_gcp_vpc.go, alkira/resource_alkira_connector_gcp_vpc_helper.go, docs/resources/connector_gcp_vpc.md, docs/resources/policy_prefix_list.md
Fix the diff generated due to gcp_routing block in connector_gcp_vpc.
=> AK-37998 Fix the diff of resource connector_gcp_vpc

alkira/resource_alkira_policy_nat_rule.go, alkira/resource_alkira_policy_nat_rule_helper.go, docs/resources/policy_nat_rule.md, go.mod, go.sum, vendor/github.com/alkiranet/alkira-client-go/alkira/policy_nat_rules.go, vendor/modules.txt
Set the default value of src_addr_translation_match_and_invalidate to true in policy_nat_rules.
=> AK-39226 Set default value of field in policy_nat_rules

alkira/resource_alkira_policy_nat_rule.go
DNAT don't support DYNAMIC_IP_AND_PORT type.
=> AK-40374 Destination NAT support STATIC_PORT and STATIC_IP_AND_PORT

.github/workflows/acceptance-preprod.yml, .github/workflows/acceptance-prod.yml, acceptance/service_pan.tf, alkira/resource_alkira_connector_ipsec.go, alkira/resource_alkira_connector_ipsec_tunnel_profile.go, docs/resources/connector_ipsec.md, docs/resources/connector_ipsec_tunnel_profile.md
Update both connector_ipsec and connector_ipsec_tunnel_profile to allow ipsec_dh_group to accept value NONE.
=> AK-41320 Update IPSec DH_GROUP to accept NONE value

alkira/resource_alkira_connector_remote_access.go, alkira/resource_alkira_connector_remote_access_helper.go, docs/resources/connector_remote_access.md, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_remote_access_template.go
Added the banner text field in remote access connector.
=> Ak 45638 remote banner text

alkira/resource_alkira_connector_aws_vpc.go, alkira/resource_alkira_connector_azure_vnet.go, alkira/resource_alkira_connector_gcp_vpc.go, docs/resources/connector_aws_vpc.md, docs/resources/connector_azure_vnet.md, docs/resources/connector_gcp_vpc.md
Update documentation of connectors to specify the credential resource.
=> AK-45894 Update documentation for credential references

vendor/github.com/alkiranet/alkira-client-go/alkira/connector_azure_expressroute.go
=> AK-46247 Correct the mac_gateway_address in connector_azure_expressroute

alkira/resource_alkira_service_fortinet.go
add check for managementServer
=> AK-46415 Add validation to service-fortinet to avoid empty managementServer

alkira/resource_alkira_service_infoblox.go, alkira/resource_alkira_service_infoblox_helper.go, vendor/github.com/alkiranet/alkira-client-go/alkira/service_infoblox.go
Add a new computed value `service_group_id` to infoblox service
=> AK-46737 - add service_group_id

alkira/resource_alkira_byoip_prefix.go
missed setting the cloud_provider in the payload.
=> AK-47328 - cloud_provider wasn't being sent in the payload

alkira/resource_alkira_service_infoblox.go, alkira/resource_alkira_service_infoblox_helper.go, docs/resources/service_infoblox.md, vendor/github.com/alkiranet/alkira-client-go/alkira/service_infoblox.go
expose `serviceGroupImplicitGroupId` computed value in TF.
=> AK-47267 - expose `serviceGroupImplicitGroupId` computed value in TF.

alkira/resource_alkira_service_checkpoint.go, alkira/resource_alkira_service_fortinet.go, alkira/resource_alkira_service_fortinet_helper.go, alkira/resource_alkira_service_infoblox.go, alkira/resource_alkira_service_pan.go
Updating service level credential now works for Checkpoint, Fortinet, Infoblox and PAN.
=> AK-47824 - Support updating service credentials

alkira/resource_alkira_service_f5_lb.go, docs/resources/service_f5_lb.md, vendor/github.com/alkiranet/alkira-client-go/alkira/service_f5_lb.go
Add `implicit_group_id` to F5 service.
=> AK-52645 - Add `implicit_group_id` to F5 service.

alkira/resource_alkira_service_f5_lb.go, docs/resources/service_f5_lb.md, vendor/github.com/alkiranet/alkira-client-go/alkira/connector_aws_tgw.go
support BEST and BETTER deployment-type for F5 for `PAY_AS_YOU_GO` `license_type`
=> AK-55767 - support `BETTER` and `BEST` `deployment_option` for F5

alkira/resource_alkira_connector_azure_expressroute_helper.go
=> AK-56112 - disable_internet_exit wasn't being set properly.

acceptance/lists.tf, acceptance/service_checkpoint.tf, alkira/resource_alkira_policy_nat_rule.go, alkira/resource_alkira_policy_nat_rule_helper.go, docs/resources/policy_nat_rule.md
Reverts alkiranet/terraform-provider-alkira#382
=> Revert "AK-55834 - update nat rules policy"

alkira/resource_alkira_probe_https.go, docs/resources/probe_https.md
take only the network_entity_id
=> AK-56774 - simplify the network_entity 
